# fly.toml app configuration file generated for pokedex-little-feather-4229 on 2024-12-11T13:19:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app            = "pokedex-little-feather-4229"
primary_region = "cdg"

[build]

[env]
PORT = "3000"

[deploy]
strategy = "canary"

[processes]
app = "node app.js"

[http_service]
internal_port        = 3000
force_https          = true
auto_stop_machines   = "stop"
auto_start_machines  = true
min_machines_running = 0
processes            = ["app"]

[[http_service.checks]]
grace_period = "10s"
interval     = "30s"
method       = "GET"
timeout      = "5s"
path         = "/health"

[[vm]]
memory   = "1gb"
cpu_kind = "shared"
cpus     = 1
